---
new_page_extension: md
auto_deploy: true
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - page
- type: document
  path: config.yml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PHP_VERSION=7.2
  - CECIL_VERSION=4.21.2
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/usr/src"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
